apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: default
type: Opaque
data:
  vsphereHost: my-vsphere.my-domain.com
  vsphereUsername: administrator@vsphere.local
  vspherePassword: supersecret
  vsphereInsecureSSL: true
  userData: "..."
